name_length: 50
email_length: 250
phone_max_length: 20
address_max_length: 250
password_min_length: 6
checked: "1"
avatar_size: 150
index_per_page: 20
avatar_small: 50
max_upload_size: 5
min_quantity: 1
rates: !ruby/range 1..5
fee: 0.05

